### PR TITLE
Could not open mmtile file!

### PR DESCRIPTION
**Pull request by Jinsheng-Peng**
Hello Developers，first of all, thank you for your efforts. This is not a bug, but I don't know how to deal with it. My map is generated by **Elysium.Extractors.18.March**, but it can't be used now.Do I need to regenerate a new map with the lh-server/core Extractors or have a url to download it?

the console just show me like this:
`MMAP:loadMap: Could not open mmtile file 'data/mmaps/0000235.mmtile'

MMAP:loadMap: Could not open mmtile file 'data/mmaps/0000335.mmtile'

MMAP:loadMap: Could not open mmtile file 'data/mmaps/0000435.mmtile'

MMAP:loadMap: Could not open mmtile file 'data/mmaps/0000535.mmtile'
.....
`
all the mmtile file Could not be opened!!

### CODE REVIEW

**Comment by bladezLH** [comment]
Make sure the files are in the configured data directory

**Comment by Jinsheng-Peng** [comment]
@bladezLH  Of course, I'm sure that my files(dbc maps vmaps mmaps) are all here. mapsData  is copy from “Lights Hope bropack v9.rar”, my last version (release 2017.1.3 with this data runs ok) and I also try to use the LH_Core tools, but the MoveMapGen.exe  always wrong and can't be generated.

**Comment by Jinsheng-Peng** [comment]
@bladezLH  I compiled a release branch and target X64.  

yes ，the mmaps file can not be found。

Is it because the current version is not compatible with the previous version of the mmap?

**Comment by ratkosrb** [comment]
There have been no changes to maps. Did you try if it works in game?

**Comment by Jinsheng-Peng** [comment]
@ratkosrb I try it. No problem at the beginning, but after playing for a while, the server crashed, prompting the map to go wrong。

the info.log show this :
`\server\src\game\Maps\MoveMap.cpp:173: Error: Assertion in MMAP::MMapManager::loadMap failed: data
2018-04-12 15:38:43 [0x12641a9]
[0x1263b64]
[0x11c5afa]
[0x11c2368]
[0x11c24dc]
[0x112eeba]
[0x112c7fe]
[0x11370b2]
[0x11a3173]
[0x1170b6e]
[0x116fc47]
[0x11a7785]
[0x11ce456]
[0x11ccb8c]
[0x11c1f4f]
[0x125ab18]
[0x73a43872]
[0x734862a4]
[0x7746336a]
[0x779e9902]
[0x779e98d5]`

so i set the loglevel = 3 and see many tips like 
`MMAP:loadMap: Could not open mmtile file 'data/mmaps/0000235.mmtile'

**Comment by ratkosrb** [comment]
Those errors always appear with loglevel=3, they are not new.

**Pull request closed without merging**
