### PR TITLE
Update Unit.cpp windfury fix

### PR DESCRIPTION
**Pull request by knasen88**
windfury fix
https://github.com/LightsHope/issues/issues/1013
I have no idea why it lists additions and deletions of several stuff while the only thing i ever did was add
// before reset attack timer and the github issue 
this is the part i edited https://i.imgur.com/9PskpXY.png

### CODE REVIEW

**Comment by dorkyo** [comment]
Is this a fix to windfury resetting the swing timer? :o

**Comment by knasen88** [comment]
yes, not just windfury though, all extra attack mechanics.

**Comment by dorkyo** [comment]
Beautiful :D

**Review by Azizxoxo — APPROVED** [review]

**Comment by bladezLH** [comment]
This change affects all extra attacks. Evidence linked in the issue points to the contrary - where it is described repeatedly that SS for example DOES reset swing timers. For us to implement a change to these mechanics which will greatly impact melee DPS (much higher), we need conclusive evidence.

While I have an idea of how they implemented it based on the patch notes from 1.4 and 2.1, in that yellows do not reset the swing timers, and Windfury itself would fall into this category, it is a huge call to make.

Either way, closing this PR since it is incorrect.

**Pull request closed without merging**
