### PR TITLE
Prevent totems attacking neutral targets

### PR DESCRIPTION
**Pull request by GuybrushGit**
Unless that target is in combat with the owner.

### CODE REVIEW

**Comment by nungerlol** [comment]
Will this fix apply to hunter traps at well?

**Comment by GuybrushGit** [comment]
No.

**Comment by nungerlol** [comment]
Hunter traps suffer from the same issue as totems. I.e. if a non-flagged hunter places a trap, the opposing faction stepping on the trap activates it and flags the hunter for pvp. Just checking if this would be easier to fix at the same time as totems.

**Comment by GuybrushGit** [comment]
Added a check to prevent attacking players if the owner has pvp disabled.

**Pull request merged**
