### PR TITLE
EK - Booty Bay

### PR DESCRIPTION
**Pull request by Tobschinski**
WPs

### CODE REVIEW

**Comment by ratkosrb** [comment]
Bruiser 715 had its spawn position corrected by me when i was working on the New Year's Eve event to match this vanilla video.
https://youtu.be/pZ7KyFiceUs?t=44s

You can see that in the video he is asleep at this exact spot. I see after your changes, there are several guards that pass through that spot, so maybe he was just there when the event started and he fell asleep?

**Comment by Tobschinski** [comment]
I think the guard in the video is 695, 715 does no longer go there.

**Comment by Tobschinski** [comment]
But I'm not familiar with the event, what happened there? Why were the guards disabled and by who?

**Comment by ratkosrb** [comment]
On New Year's Eve all the Booty Bay Bruisers get drunk and turn into [Drunken Bruisers](https://classicdb.ch/?npc=15724). This allows you to PvP without fear of the guards, as they are all sleeping. You can see it in the video i linked.

https://wow.gamepedia.com/Drunken_Bruiser

**Comment by Tobschinski** [comment]
Well, the video is indeed interesting. I see a few patrolling guards that sleep (at least) extremely close to their spawn points, others are way off. Blizzard would however not spawn creatures in the middle of their path, it's usually at the corner points. So I guess the creature just happen to be at that point when it cast 26115 on itself.

That's my guess, but I cannot guarantee I am correct here.
But I also do not see a reason why they would move the guard at a later patch, BB hasn't changed since vanilla.

**Pull request merged**
