### PR TITLE
Stratholme - Patchwork Horror

### PR DESCRIPTION
**Pull request by Tobschinski**
Knock Away (10101) reduces the target's threat by 100%. (ability is used by more creatures, Alzzin in DME or even in AQ40)

### CODE REVIEW

**Comment by Tobschinski** [comment]
There will be more Knock Away variants, e.g. Molten Giants ...

**Comment by ratkosrb** [comment]
Hey, I just want to let you know we have an editor for `creature_spells` templates that you can use to avoid working with raw sql. It generates the query for you when you press the save button.

creature_spells
https://github.com/brotalnia/ScriptEditor/releases

**Comment by Tobschinski** [comment]
I'll check that out, thanks.

**Comment by Tobschinski** [comment]
Oh, forgot my sources. Sniffs ofc and...

untitled

From the BG Dungeon Guide, for Qiraji Slayers.

**Pull request merged**
