### PR TITLE
Dire Maul - East

### PR DESCRIPTION
**Pull request by Tobschinski**
lots of missing creatures added

### CODE REVIEW

**Comment by brotalnia** [comment]
Is this based on sniffs? I've included this in my repack and have gotten some feedback saying the changes are quite drastic.

**Comment by Tobschinski** [comment]
Yep, everything I PR is. What do they not like about it?

**Comment by brotalnia** [comment]
I was told there are a lot of extra spawns that make it impossible to farm there as a mage. They don't remember it being this way on retail.

**Comment by Tobschinski** [comment]
It's been 13 years, memories can be off, especially if you played all the private servers who did not have the correct amount of mobs.

[This priest here](https://youtu.be/M3zA1qH02VA?t=124) does a full clear, you can see every group of Whip Lashers (8 * 10) and most, if not all, Death Lashes (11) and Warpwood Treants (5 * 3).

Anyway, I tried this myself and I had no problems to cross the courtyard without pulling a single mob.  And if you know the patrols, farming will be just as easy.

**Pull request merged**
