### PR TITLE
Classic melee formulas

### PR DESCRIPTION
**Pull request by GuybrushGit**
Formulas based on Beaza's writings, the recent blue posts and Classic Beta testing: https://github.com/magey/classic-warrior/wiki/Attack-table

Some things that are still unknown / up to debate:
- How exactly parry scales. I made it a linear 0.6 per skill point so it matches the 14% but the data shows much lower parry than expected on +1 and +2 level mobs.
- Beaza never mentions what he means by "caster" on the glancing formula. I considered caster to be only the wand classes Mage / Lock / Priest.
- I hardcoded the mysterious 1% of hit that gets ignored according to the latest blue post, even though it makes no sense and it could just be the QA person explaining it badly. Let me know if I should remove it.

### CODE REVIEW

**Comment by GuybrushGit** [comment]
Updated dodge and block to be affected by weapon skill above max.
Attacks with fishing rod with +100 skill reduced dodge and block to 0%:

> Crit chance: 3.88%
> Attacks: 1673
> Hit: 45.37% ±2.43% (759)
> Crit: 1.14% ±0.52% (19)
> Miss: 0.00% ±0.00% (0)
> Parry: 12.25% ±1.60% (205)
> Dodge: 0.00% ±0.00% (0)
> Block: 0.00% ±0.00% (0)
> Glancing: 41.24% ±2.41% (690)
> Glance Reduction: ~4.86%

**Comment by mako-taco** [comment]
If you keep parry scaling at 0.04% (as previous blue posts have stated) and then add a flat 9% to the total (if there's a level gap > 2) will more closely approximate the empirical data.

**Comment by GuybrushGit** [comment]
Not a fan of adding a flat 9% and mixing in the pvp modifier, its very unlike the other formulas, don't think Blizzard would do something like that.

My best guess would be either a 0.1 or 0.2 modifier for skillDiffs >= -10 similar to how hit chance has a different modifier for >= -10. This would give 61/62/63 a 5.5/6/14 or 6/7/14 chance to parry.

**Comment by mako-taco** [comment]
The formulas in place right now are so convoluted that there is almost no chance they actually match what blizzards were.

The formula we know the most about is dodge, from blue posts:
```
5% + (level difference) * 0.5%
```
And from ancient blue posts on weapon skill that state it reduces the chance to X by 0.04% per point, I think it's reasonable to assume this:
```
5% + (level difference) * 0.5% + (def skill - weapon skill) * 0.04
```
This is so incredibly simple. When you apply the same constants to parry, you get another simple formula that matches our data for 0-2 level difference:
```
5% + (level difference) * 0.5% + (def skill - weapon skill) * 0.04
``` 
All thats left now is the mechanism for stepping us to 14% when there's a large level gap. Changing the coefficient for level difference based on a large level gap is simple, and fits the data.
```
5% + (level difference) * (level difference > 2 ? %3 : 0.5%) + (def skill - weapon skill) * 0.04
```

**Pull request merged**
