### PR TITLE
Quest experience overhaul

### PR DESCRIPTION
**Pull request by GuybrushGit**
Major quest experience rewards adjustment.

1721 quests could be automated from Thotbott. All remaining quests were manually checked against the Master Guide.

Overall 2130 quests were changed with an average of 30% lower XP reward.

### CODE REVIEW

**Comment by Soyoen** [comment]
[MG WoWC QValues.xlsx](https://github.com/lh-server/core/files/1875278/MG.WoWC.QValues.xlsx)

MG WoW:C quest values (Minimum level+Experience rewards) accessible via excel.

**Comment by GuybrushGit** [comment]
Wheres that from? You parse them yourself from the guide?

**Comment by GuybrushGit** [comment]
Comparison with our DB, only the ones with a diferent value:
https://docs.google.com/spreadsheets/d/1Q1KhpqTey2rRKJPtPRizBAI9YDHp7AggHC-nqJh58IM/edit#gid=1132333490

Seems like for some your Excel is right and for others the DB is right.

**Comment by Kittnz** [comment]
i guess it depence on patch

**Comment by Soyoen** [comment]
@GuybrushGit I parsed them from the guide and entered the values into a DB dump a good year ago, that's a great comparison to find errors especially considering MG does in general not contain dungeon quests so those not in MG were parsed from thott/alla values & comments (and still a pain to checkup in MG now in retrospec). I hope that implies that the minlevel for everything is correct as well throughout with these recent changes.

4041 should be 0 as you had it.
1156, 1157, 1158 should be removed.
Shadowshard fragments should as you had it be 3450. http://web.archive.org/web/20070516000603/http://www.thottbot.com:80/q7044
Plainsrunning is for the taurens in alpha/beta so in 1.12 it's not relevant
Perfect yeti hide should be 440 in vanilla as you had it: The quest was nerfed as it was repeatable meaning people could turn it in over and over for easy 2200xp each time (which would make it 2200 for early patches and lateron 440). Funny enough it appears the Alliance version of the quest was not nerfed until TBC. http://web.archive.org/web/20070527165054/http://www.thottbot.com:80/q7738
909 values in the document are incorrect, yours is correct after looking into it further.
787: http://web.archive.org/web/20050501045944/http://wow.allakhazam.com:80/db/quest.html?wquest=787
6183: 650xp
6961 correct on your side
Can't find anything in MG about 2201, yours is correct.

**Comment by GuybrushGit** [comment]
I'm going through all the ones that were different one by one, they're mostly level 60 quests that I didn't bother with when doing this pull. 450 done 150 to go.

**Pull request merged**
